import os
from datetime import date
from pathlib import Path

import markdown as md_lib

from backend.models import ResearchFinding


OUTPUTS_DIR = Path(__file__).resolve().parents[2] / "outputs"


class WriterAgent:
    def __init__(self):
        OUTPUTS_DIR.mkdir(exist_ok=True)

    def write(
        self,
        query: str,
        subquestions: list[str],
        findings: list[ResearchFinding],
        synthesis: dict,
    ) -> tuple[str, str, str]:
        markdown_content = self._build_markdown(query, findings, synthesis)

        safe_name = "".join(
            c if c.isalnum() or c in (" ", "-", "_") else "_" for c in query
        )
        safe_name = safe_name[:60].strip().replace(" ", "_")
        today = date.today().strftime("%Y-%m-%d")
        base_name = f"{today}_{safe_name}"

        md_path = OUTPUTS_DIR / f"{base_name}.md"
        pdf_path = OUTPUTS_DIR / f"{base_name}.pdf"

        md_path.write_text(markdown_content, encoding="utf-8")
        self._generate_pdf(markdown_content, pdf_path)

        return md_path.name, pdf_path.name, markdown_content

    def _build_markdown(
        self,
        query: str,
        findings: list[ResearchFinding],
        synthesis: dict,
    ) -> str:
        today = date.today().strftime("%B %d, %Y")
        lines = []

        lines.append(f"# Research Report: {query}")
        lines.append(f"\n**Date:** {today}  ")
        lines.append(f"**Generated by:** Autonomous Research Agent\n")
        lines.append("---\n")

        # Executive Summary
        lines.append("## Executive Summary\n")
        lines.append(synthesis.get("executive_summary", "") + "\n")

        # Key Findings
        key_findings = synthesis.get("key_findings", [])
        if key_findings:
            lines.append("## Key Findings\n")
            for kf in key_findings:
                lines.append(f"- {kf}")
            lines.append("")

        # Sections per subquestion
        sections = synthesis.get("sections", [])
        if sections:
            lines.append("## Detailed Analysis\n")
            for section in sections:
                subq = section.get("subquestion", "")
                analysis = section.get("analysis", "")
                lines.append(f"### {subq}\n")
                lines.append(analysis + "\n")

        # Tradeoffs / Comparisons
        tradeoffs = synthesis.get("tradeoffs", [])
        if tradeoffs:
            lines.append("## Tradeoffs & Comparisons\n")
            for t in tradeoffs:
                lines.append(f"- {t}")
            lines.append("")

        # Comparison Table
        table_rows = synthesis.get("comparison_table", [])
        if table_rows:
            lines.append("## Comparison Table\n")
            lines.append("| Aspect | Details |")
            lines.append("|--------|---------|")
            for row in table_rows:
                aspect = row.get("aspect", "").replace("|", "\\|")
                details = row.get("details", "").replace("|", "\\|")
                lines.append(f"| {aspect} | {details} |")
            lines.append("")

        # Conclusion
        conclusion = synthesis.get("conclusion", "")
        if conclusion:
            lines.append("## Conclusion\n")
            lines.append(conclusion + "\n")

        # Sources
        lines.append("## Sources\n")
        source_num = 1
        for finding in findings:
            lines.append(f"### {finding.subquestion}\n")
            for source in finding.sources:
                if source.url:
                    lines.append(f"{source_num}. [{source.title}]({source.url})")
                    source_num += 1
            lines.append("")

        lines.append("---")
        lines.append("*Report generated by Autonomous Research Agent*")

        return "\n".join(lines)

    def _generate_pdf(self, markdown_content: str, output_path: Path) -> None:
        try:
            from weasyprint import HTML

            html_body = md_lib.markdown(
                markdown_content,
                extensions=["tables", "fenced_code"],
            )
            full_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{
    font-family: Georgia, serif;
    max-width: 800px;
    margin: 40px auto;
    padding: 0 20px;
    line-height: 1.7;
    color: #222;
  }}
  h1 {{ color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }}
  h2 {{ color: #16213e; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 32px; }}
  h3 {{ color: #0f3460; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th, td {{ border: 1px solid #ccc; padding: 8px 12px; text-align: left; }}
  th {{ background: #f0f0f0; font-weight: bold; }}
  a {{ color: #0f3460; }}
  code {{ background: #f4f4f4; padding: 2px 4px; border-radius: 3px; font-size: 0.9em; }}
  hr {{ border: none; border-top: 1px solid #ccc; margin: 24px 0; }}
  ul, ol {{ padding-left: 24px; }}
  li {{ margin-bottom: 4px; }}
  em {{ color: #555; font-size: 0.9em; }}
</style>
</head>
<body>
{html_body}
</body>
</html>"""
            HTML(string=full_html).write_pdf(str(output_path))
        except Exception as e:
            # Write a minimal error PDF placeholder text file so download still works
            output_path.write_text(
                f"PDF generation failed: {e}\n\nSee the .md file for the full report.",
                encoding="utf-8",
            )
