import os
from datetime import date
from pathlib import Path

from fpdf import FPDF

from backend.models import ResearchFinding


OUTPUTS_DIR = Path(__file__).resolve().parents[2] / "outputs"

FONT_DIR = Path("/System/Library/Fonts/Supplemental")
FONT_REGULAR = str(FONT_DIR / "Arial.ttf")
FONT_BOLD = str(FONT_DIR / "Arial Bold.ttf")
FONT_ITALIC = str(FONT_DIR / "Arial Italic.ttf")
FONT_BOLD_ITALIC = str(FONT_DIR / "Arial Bold Italic.ttf")


class WriterAgent:
    def __init__(self):
        OUTPUTS_DIR.mkdir(exist_ok=True)

    def write(
        self,
        query: str,
        subquestions: list[str],
        findings: list[ResearchFinding],
        synthesis: dict,
    ) -> tuple[str, str, str]:
        markdown_content = self._build_markdown(query, findings, synthesis)

        safe_name = "".join(
            c if c.isalnum() or c in (" ", "-", "_") else "_" for c in query
        )
        safe_name = safe_name[:60].strip().replace(" ", "_")
        today = date.today().strftime("%Y-%m-%d")
        base_name = f"{today}_{safe_name}"

        md_path = OUTPUTS_DIR / f"{base_name}.md"
        pdf_path = OUTPUTS_DIR / f"{base_name}.pdf"

        md_path.write_text(markdown_content, encoding="utf-8")
        self._generate_pdf(query, findings, synthesis, pdf_path)

        return md_path.name, pdf_path.name, markdown_content

    def _build_markdown(
        self,
        query: str,
        findings: list[ResearchFinding],
        synthesis: dict,
    ) -> str:
        today = date.today().strftime("%B %d, %Y")
        lines = []

        lines.append(f"# Research Report: {query}")
        lines.append(f"\n**Date:** {today}  ")
        lines.append(f"**Generated by:** Autonomous Research Agent\n")
        lines.append("---\n")

        lines.append("## Executive Summary\n")
        lines.append(synthesis.get("executive_summary", "") + "\n")

        key_findings = synthesis.get("key_findings", [])
        if key_findings:
            lines.append("## Key Findings\n")
            for kf in key_findings:
                lines.append(f"- {kf}")
            lines.append("")

        sections = synthesis.get("sections", [])
        if sections:
            lines.append("## Detailed Analysis\n")
            for section in sections:
                lines.append(f"### {section.get('subquestion', '')}\n")
                lines.append(section.get("analysis", "") + "\n")

        tradeoffs = synthesis.get("tradeoffs", [])
        if tradeoffs:
            lines.append("## Tradeoffs & Comparisons\n")
            for t in tradeoffs:
                lines.append(f"- {t}")
            lines.append("")

        table_rows = synthesis.get("comparison_table", [])
        if table_rows:
            lines.append("## Comparison Table\n")
            lines.append("| Aspect | Details |")
            lines.append("|--------|---------|")
            for row in table_rows:
                aspect = row.get("aspect", "").replace("|", "\\|")
                details = row.get("details", "").replace("|", "\\|")
                lines.append(f"| {aspect} | {details} |")
            lines.append("")

        conclusion = synthesis.get("conclusion", "")
        if conclusion:
            lines.append("## Conclusion\n")
            lines.append(conclusion + "\n")

        lines.append("## Sources\n")
        source_num = 1
        for finding in findings:
            lines.append(f"### {finding.subquestion}\n")
            for source in finding.sources:
                if source.url:
                    lines.append(f"{source_num}. [{source.title}]({source.url})")
                    source_num += 1
            lines.append("")

        lines.append("---")
        lines.append("*Report generated by Autonomous Research Agent*")

        return "\n".join(lines)

    def _generate_pdf(
        self,
        query: str,
        findings: list[ResearchFinding],
        synthesis: dict,
        output_path: Path,
    ) -> None:
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()
        pdf.set_margins(20, 20, 20)

        # Register Arial as a Unicode TTF font family
        pdf.add_font("Arial", style="", fname=FONT_REGULAR)
        pdf.add_font("Arial", style="B", fname=FONT_BOLD)
        pdf.add_font("Arial", style="I", fname=FONT_ITALIC)
        pdf.add_font("Arial", style="BI", fname=FONT_BOLD_ITALIC)

        today = date.today().strftime("%B %d, %Y")

        def add_h1(text: str):
            pdf.set_font("Arial", "B", 18)
            pdf.set_text_color(26, 26, 46)
            pdf.multi_cell(0, 10, text)
            pdf.ln(2)
            pdf.set_draw_color(26, 26, 46)
            pdf.set_line_width(0.5)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(6)
            pdf.set_text_color(0, 0, 0)

        def add_h2(text: str):
            pdf.ln(4)
            pdf.set_font("Arial", "B", 13)
            pdf.set_text_color(22, 33, 62)
            pdf.multi_cell(0, 8, text)
            pdf.set_draw_color(200, 200, 200)
            pdf.set_line_width(0.3)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(4)
            pdf.set_text_color(0, 0, 0)

        def add_h3(text: str):
            pdf.ln(3)
            pdf.set_font("Arial", "B", 11)
            pdf.set_text_color(15, 52, 96)
            pdf.multi_cell(0, 7, text)
            pdf.ln(2)
            pdf.set_text_color(0, 0, 0)

        def add_body(text: str):
            pdf.set_font("Arial", "", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 6, text)
            pdf.ln(2)
            pdf.set_text_color(0, 0, 0)

        def add_bullet(text: str):
            pdf.set_font("Arial", "", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.set_x(25)
            pdf.multi_cell(165, 6, f"•  {text}")
            pdf.set_text_color(0, 0, 0)

        # Title
        add_h1(f"Research Report: {query}")
        pdf.set_font("Arial", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 6, f"Date: {today}   |   Generated by Autonomous Research Agent")
        pdf.ln(8)
        pdf.set_text_color(0, 0, 0)

        # Executive Summary
        exec_summary = synthesis.get("executive_summary", "")
        if exec_summary:
            add_h2("Executive Summary")
            add_body(exec_summary)

        # Key Findings
        key_findings = synthesis.get("key_findings", [])
        if key_findings:
            add_h2("Key Findings")
            for kf in key_findings:
                add_bullet(kf)
            pdf.ln(2)

        # Detailed Analysis
        sections = synthesis.get("sections", [])
        if sections:
            add_h2("Detailed Analysis")
            for section in sections:
                add_h3(section.get("subquestion", ""))
                add_body(section.get("analysis", ""))

        # Tradeoffs
        tradeoffs = synthesis.get("tradeoffs", [])
        if tradeoffs:
            add_h2("Tradeoffs & Comparisons")
            for t in tradeoffs:
                add_bullet(t)
            pdf.ln(2)

        # Comparison Table
        table_rows = synthesis.get("comparison_table", [])
        if table_rows:
            add_h2("Comparison Table")
            col_w = [70, 110]
            pdf.set_font("Arial", "B", 9)
            pdf.set_fill_color(240, 240, 240)
            pdf.cell(col_w[0], 8, "Aspect", border=1, fill=True)
            pdf.cell(col_w[1], 8, "Details", border=1, fill=True)
            pdf.ln()
            pdf.set_font("Arial", "", 9)
            for row in table_rows:
                pdf.cell(col_w[0], 7, str(row.get("aspect", ""))[:50], border=1)
                pdf.cell(col_w[1], 7, str(row.get("details", ""))[:90], border=1)
                pdf.ln()
            pdf.ln(4)

        # Conclusion
        conclusion = synthesis.get("conclusion", "")
        if conclusion:
            add_h2("Conclusion")
            add_body(conclusion)

        # Sources
        add_h2("Sources")
        source_num = 1
        for finding in findings:
            add_h3(finding.subquestion)
            for source in finding.sources:
                if source.url:
                    pdf.set_font("Arial", "", 9)
                    pdf.set_text_color(40, 40, 40)
                    pdf.set_x(25)
                    pdf.multi_cell(165, 5, f"{source_num}. {source.title}")
                    pdf.set_font("Arial", "I", 8)
                    pdf.set_text_color(60, 60, 180)
                    pdf.set_x(28)
                    pdf.multi_cell(162, 5, source.url)
                    pdf.set_text_color(0, 0, 0)
                    source_num += 1
            pdf.ln(2)

        pdf.output(str(output_path))
